version: '3'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  calc-server:
    build:
      context: ./calc-server-nats-docker/poetry-demo
    depends_on:
      - nats
    # Add your calc-server command here

  fastapi-server:
    build:
      context: ./server-fastapi-comm-to-nats-docker/poetry-demo
    depends_on:
      - calc-server
    # Add your FastAPI server command here
    ports:
      - 8000:8000

  client:
    build:
      context: ./client-for-fastapi-server-to-nats-docker/poetry-demo
    depends_on:
      - fastapi-server
    # Add your client command here
    stdin_open: true
